### PR TITLE
Python 3

### PR DESCRIPTION
**Pull request by giorgiosironi**
3.5 will be the only supported version, as this is a project and not a library.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Current error:
```
17:54:52 _____________________ ERROR collecting test_journal_cms.py _____________________
17:54:52 venv/lib/python3.5/site-packages/_pytest/python.py:611: in _importtestmodule
17:54:52     mod = self.fspath.pyimport(ensuresyspath=importmode)
17:54:52 venv/lib/python3.5/site-packages/py/_path/local.py:650: in pyimport
17:54:52     __import__(modname)
17:54:52 spectrum/test_journal_cms.py:4: in <module>
17:54:52     from spectrum import input
17:54:52 spectrum/input.py:8: in <module>
17:54:52     from spectrum import aws, logger
17:54:52 spectrum/aws.py:13: in <module>
17:54:52     region_name=SETTINGS['region_name']
17:54:52 venv/lib/python3.5/site-packages/boto3/__init__.py:92: in resource
17:54:52     return _get_default_session().resource(*args, **kwargs)
17:54:52 venv/lib/python3.5/site-packages/boto3/session.py:389: in resource
17:54:52     aws_session_token=aws_session_token, config=config)
17:54:52 venv/lib/python3.5/site-packages/boto3/session.py:263: in client
17:54:52     aws_session_token=aws_session_token, config=config)
17:54:52 venv/lib/python3.5/site-packages/botocore/session.py:824: in create_client
17:54:52     client_config=config, api_version=api_version)
17:54:52 venv/lib/python3.5/site-packages/botocore/client.py:63: in create_client
17:54:52     cls = self._create_client_class(service_name, service_model)
17:54:52 venv/lib/python3.5/site-packages/botocore/client.py:85: in _create_client_class
17:54:52     base_classes=bases)
17:54:52 venv/lib/python3.5/site-packages/botocore/hooks.py:227: in emit
17:54:52     return self._emit(event_name, kwargs)
17:54:52 venv/lib/python3.5/site-packages/botocore/hooks.py:210: in _emit
17:54:52     response = handler(**kwargs)
17:54:52 venv/lib/python3.5/site-packages/boto3/utils.py:61: in _handler
17:54:52     module = import_module(module)
17:54:52 venv/lib/python3.5/site-packages/boto3/utils.py:52: in import_module
17:54:52     __import__(name)
17:54:52 venv/lib/python3.5/site-packages/boto3/s3/inject.py:13: in <module>
17:54:52     from s3transfer.manager import TransferManager, TransferConfig
17:54:52 venv/lib/python3.5/site-packages/s3transfer/__init__.py:134: in <module>
17:54:52     import concurrent.futures
17:54:52 venv/lib/python3.5/site-packages/concurrent/futures/__init__.py:8: in <module>
17:54:52     from concurrent.futures._base import (FIRST_COMPLETED,
17:54:52 E     File "/ext/srv/elife-spectrum/venv/lib/python3.5/site-packages/concurrent/futures/_base.py", line 357
17:54:52 E       raise type(self._exception), self._exception, self._traceback
17:54:52 E                                  ^
17:54:52 E   SyntaxError: invalid syntax
```

**Comment by giorgiosironi** [comment]
I have a different file locally. And it passes the same test. Trying to reset the venv then.

**Comment by giorgiosironi** [comment]
Still getting the same error, but at least I have the same `venv` locally.
@seanwiseman any pointers? Is that `raise` valid syntax in 3.5?

**Comment by seanwiseman** [comment]
In `py2` the raise syntax is `raise {type}, {value}, {traceback}`, in `py3` its `raise {exception_object}`. The latter just raises the actual exception object as a whole. 

If you try to use the `py2` way in `py3` you get the `SyntaxError` you see. If you want to just assist me getting this setup locally I can troubleshoot it further for you if you like?

**Comment by giorgiosironi** [comment]
I have given you access to `elife-alfred` stacks to allow for download of the `app.cfg` needed to run the tests. At the moment we have some stability problems so I'll postpone this.

**Comment by seanwiseman** [comment]
OK thank you. Just let me know once its fine to try it out.

**Comment by giorgiosironi** [comment]
Will close and reopen as a cleanup of the repository is needed first.

**Pull request closed without merging**
