### PR TITLE
ELPP-3445 Change subject of an article through silent correction

### PR DESCRIPTION
**Pull request by giorgiosironi**
I am using the article `elife-15893-v1` as a template.

The configuration file uploaded to `end2end-elife-bot` has:

```
$ cat article_subjects.csv 
DOI,subj-group-type,subject
10.7554/eLife.32656,heading,Biochemistry and Chemical Biology
```

but the subjects do not get rewritten:

```
curl -s https://end2end--gateway.elifesciences.org/articles/134820053256315893 | jq .subjects
[
  {
    "name": "Biochemistry",
    "id": "biochemistry"
  },
  {
    "name": "Biophysics and Structural Biology",
    "id": "biophysics-structural-biology"
  }
]
```

`worker.log` says:

```
2018-02-16T16:16:59Z INFO worker_1394 activityType: ModifyArticleSubjects
...
2018-02-16T16:16:59Z INFO worker_1394 did not modify any article subjects in the article xml
```

(the test is missing the assertion for now, I was doing the check manually)

### CODE REVIEW

**Comment by gnott** [comment]
Is the article number in the above ``134820053256315893`` randomly generated? The subject replacements are specified in the CSV file in the bucket with a specific DOI. The tests may need to generate the CSV file to include the article data prior to attempting the workflow execution.

**Comment by giorgiosironi** [comment]
Yes, the file is dynamically generated (but it is overwritten by every new test). This is the latest used:
```
cat article_subjects.csv 
DOI,subj-group-type,subject
10.7554/eLife.5614397577281315893,heading,Immunology
```
Is `heading` something that has more than one possible value?

**Comment by giorgiosironi** [comment]
Found the problem, see https://github.com/elifesciences/elife-spectrum/pull/105/commits/2a14029a7d3a7440b39304c86647df4f2e521bb3

**Comment by gnott** [comment]
Very good, once the subfolder on S3 is included. Looks like it is getting the desired result.

**Pull request merged**
