### PR TITLE
Updated kitchen sinks from Github (elife-00777.xml,elife-00666.xml)

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-elife-spectrum-update-kitchen-sinks-github/975/display/redirect which resulted in this pull request.

### CODE REVIEW

**Comment by lsh-0** [comment]
elife-dashboard output holds the answer:

```
[2021-08-05T06:48:50.668Z] E                                      {'event-message': 'Lax has not ingested article '
[2021-08-05T06:48:50.668Z] E                                                        '4179451410532600666 result from '
[2021-08-05T06:48:50.668Z] E                                                        'lax:error; message from lax: '
[2021-08-05T06:48:50.668Z] E                                                        'failed to render article-json '
[2021-08-05T06:48:50.668Z] E                                                        'from article-xml: glencoe '
[2021-08-05T06:48:50.668Z] E                                                        "doesn't know 'app1fig1video1', "
[2021-08-05T06:48:50.668Z] E                                                        "only 'app2video1, fig3video1, "
[2021-08-05T06:48:50.668Z] E                                                        "respvideo1, video1, video2'",
[2021-08-05T06:48:50.668Z] E                                       'event-status': 'error',
```

**Comment by lsh-0** [comment]
fyi @gnott , I think we've encountered this problem before - those assets it's looking for are for the actual 00666 article, right?

**Comment by gnott** [comment]
Sounds familiar for sure, it was easy for me to find a comment of mine on a previous ticket regarding videos at Glencoe https://github.com/elifesciences/issues/issues/6214#issuecomment-720867708

**Comment by lsh-0** [comment]
that's exactly the issue I was recalling, thanks @gnott .

**Pull request closed without merging**
