### PR TITLE
Updated kitchen sinks from Github (elife-00777.xml,elife-00666.xml)

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-elife-spectrum-update-kitchen-sinks-github/437/display/redirect which resulted in this pull request.

### CODE REVIEW

**Comment by FAtherden-eLife** [comment]
@gnott @thewilkybarkid, as far as I can tell the JSON schema seems to take umbrage with the [figure](https://github.com/elifesciences/XML-mapping/blob/fc02e9c26be19ff944902962a732c377728be266/elife-00666.xml#L4368-L4377) that I added in appendix 2. 

I don't see anything incorrect with the figure markup itself - the XML is DTD valid. We have figures that are direct children of boxed-text elsewhere in the kitchen sink, and I think we need to account for this type of content capture.

Is my assumption correct (that the figure is the cause of the error), and if so what are your thoughts about relaxing the JSON specification to account for this?

**Comment by thewilkybarkid** [comment]
That's already valid JSON, we even have a test for it (https://github.com/elifesciences/api-raml/blob/90eaabd0c642a70e39f1490dda33547c7b02f678/src/samples/article-vor/v2/complete.json#L1493-L1543).

**Comment by FAtherden-eLife** [comment]
@thewilkybarkid, doesn't the above assume the figure is [in a section](https://github.com/elifesciences/api-raml/blob/90eaabd0c642a70e39f1490dda33547c7b02f678/src/samples/article-vor/v2/complete.json#L1500-L1538) (in the XML a child of <sec>)? 

[Here](https://github.com/elifesciences/XML-mapping/blob/fc02e9c26be19ff944902962a732c377728be266/elife-00666.xml#L4368-L4377) the figure is a child of <boxed-text>, which is a child of <appendix>, i.e. the figure has no parent/ancestor <sec>. I'm not as familiar with JSON as with XML, so there may well be something strikingly obvious I'm missing.

**Comment by thewilkybarkid** [comment]
The figure in the JSON is a sibling of the section.

Not seen the actual error but most probably a conversion problem, so one for @gnott.

**Comment by giorgiosironi** [comment]
If it helps, here's the JSON that gets generated by the latest `bot-lax-adaptor`:
https://gist.github.com/giorgiosironi/361fbd4eacc52ee6e46078d386ddd2e7
and this is the full validation error:
```
Failed validating 'oneOf' in schema['allOf'][2]['properties']['appendices']['items']['properties']['content']['items']:
    {'oneOf': [{'oneOf': [{'oneOf': [{'$schema': 'http://json-schema.org/draft-04/schema#',
                                      'properties': {'text': {'title': 'Text',
                                                              'type': 'string'},
                                                     'type': {'enum': ['button'],
                                                              'type': 'string'},
                                                     'uri': {'format': 'uri',
                                                             'title': 'URI',
                                                             'type': 'string'}},
                                      'required': ['type', 'text', 'uri'],
                                      'title': 'Button',
                                      'type': 'object'},
                                     {'$schema': 'http://json-schema.org/draft-04/schema#',
                                      'properties': {'code': {'description': 'Code, '
                                                                             'contain '
                                                                             'nessecary '
                                                                             'indentation '
                                                                             'and '
                                                                             'line '
                                                                             'breaks.',
                                                              'minLength': 1,
                                                              'title': 'Code',
                                                              'type': 'string'},
                                                     'language': {'description': 'For '
                                                                                 'example:\n'
                                                                                 '  '
                                                                                 '- '
                                                                                 'Python\n'
                                                                                 '  '
                                                                                 '- '
                                                                                 'Java\n'
                                                                                 '  '
                                                                                 '- '
                                                                                 'PHP\n'
                                                                                 '  '
                                                                                 '- '
                                                                                 'JavaScript\n',
                                                                  'title': 'Language '
                                                                           'name',
                                                                  'type': 'string'},
                                                     'type': {'enum': ['code'],
                                                              'type': 'string'}},
                                      'required': ['type', 'code'],
                                      'title': 'Code',
                                      'type': 'object'},
                                     {'$schema': 'http://json-schema.org/draft-04/schema#',
                                      'properties': {'cite': {'title': 'Citation',
                                                              'type': 'string'},
                                                     'content': {'description': 'Content',
                                                                 'items': {'oneOf': [{'$ref': '#/allOf/2/properties/acknowledgements/items/oneOf/0/oneOf/0/oneOf/1'},
                                                                                     {'$schema': 'http://json-schema.org/draft-04/schema#',
                                                                                      'properties': {'items': {'description': 'List '
                                                                                                                              'items',
                                                                                                               'items': {'oneOf': [{'type': 'string'},
                                                                                                                                   {'items': {'$ref': '#/allOf/2/properties/acknowledgements/items/oneOf/0/oneOf/0'},
                                                                                                                                    'minItems': 1,
                                                                                                                                    'type': 'array'}]},
                                                                                                               'minItems': 1,
                                                                                                               'type': 'array'},
                                                                                                     'prefix': {'enum': ['alpha-lower',
                                                                                                                         'alpha-upper',
                                                                                                                         'bullet',
                                                                                                                         'none',
                                                                                                                         'number',
                                                                                                                         'roman-lower',
                                                                                                                         'roman-upper'],
                                                                                                                'type': 'string'},
                                                                                                     'type': {'enum': ['list'],
                                                                                                              'type': 'string'}},
                                                                                      'required': ['type',
                                                                                                   'prefix',
                                                                                                   'items'],
                                                                                      'title': 'List',
                                                                                      'type': 'object'},
                                                                                     {'$ref': '#/allOf/1/allOf/1/properties/additionalFiles/items/allOf/0/properties/caption/items/oneOf/0'},
                                                                                     {'$ref': '#/allOf/1/allOf/1/properties/ethics/items'},
                                                                                     {'$schema': 'http://json-schema.org/draft-04/schema#',
                                                                                      'allOf': [{'$ref': '#/allOf/1/allOf/1/properties/additionalFiles/items/allOf/0'},
                                                                                                {'$ref': '#/allOf/1/allOf/1/properties/additionalFiles/items/allOf/1'},
                                                                                                {'properties': {'footnotes': {'items': {'$schema': 'http://json-schema.org/draft-04/schema#',
                                                                                                                                        'dependencies': {'id': ['label'],
                                                                                                                                                         'label': ['id']},
                                                                                                                                        'properties': {'id': {'$ref': '#/allOf/2/properties/appendices/items/properties/id'},
                                                                                                                                                       'label': {'minLength': 1,
                                                                                                                                                                 'type': 'string'},
                                                                                                                                                       'text': {'items': {'oneOf': [{'$ref': '#/allOf/1/allOf/1/properties/ethics/items'},
                                                                                                                                                                                    {'$ref': '#/allOf/1/allOf/1/properties/additionalFiles/items/allOf/0/properties/caption/items/oneOf/0'}]},
                                                                                                                                                                'minItems': 1,
                                                                                                                                                                'type': 'array'}},
                                                                                                                                        'required': ['text'],
                                                                                                                                        'title': 'Footnote',
                                                                                                                                        'type': 'object'},
                                                                                                                              'type': 'array'},
                                                                                                                'tables': {'items': {'pattern': '^<table>[\\s\\S]+</table>$',
                                                                                                                                     'title': 'HTML '
                                                                                                                                              'table',
                                                                                                                                     'type': 'string'},
                                                                                                                           'type': 'array'},
                                                                                                                'type': {'enum': ['table'],
                                                                                                                         'type': 'string'}},
                                                                                                 'required': ['type',
                                                                                                              'tables']}],
                                                                                      'title': 'Table',
                                                                                      'type': 'object'}]},
                                                                 'minItems': 1,
                                                                 'type': 'array'},
                                                     'type': {'enum': ['excerpt'],
                                                              'type': 'string'}},
                                      'required': ['type', 'content'],
                                      'title': 'Excerpt',
                                      'type': 'object'},
                                     {'$schema': 'http://json-schema.org/draft-04/schema#',
                                      'properties': {'assets': {'items': {'allOf': [{'oneOf': [{'allOf': [{'$ref': '#/allOf/2/properties/acknowledgements/items/oneOf/0/oneOf/0/oneOf/4'},
                                                                                                          {'properties': {'inline': {'enum': [False]}}}]},
                                                                                               {'$ref': '#/allOf/2/properties/acknowledgements/items/oneOf/0/oneOf/0/oneOf/2/properties/content/items/oneOf/4'},
                                                                                               {'$ref': '#/allOf/2/properties/acknowledgements/items/oneOf/0/oneOf/0/oneOf/12'}]},
                                                                                    {'properties': {'doi': {'$ref': '#/allOf/0/allOf/0/properties/doi'},
                                                                                                    'label': {'minLength': 1,
                                                                                                              'title': 'Label',
                                                                                                              'type': 'string'},
                                                                                                    'sourceData': {'items': {'$ref': '#/allOf/1/allOf/1/properties/additionalFiles/items'},
                                                                                                                   'title': 'Source '
                                                                                                                            'data',
                                                                                                                   'type': 'array'}},
                                                                                     'required': ['id',
                                                                                                  'label']}]},
                                                                'minItems': 1,
                                                                'type': 'array'},
                                                     'type': {'enum': ['figure'],
                                                              'type': 'string'}},
                                      'required': ['type', 'assets'],
                                      'title': 'Figure',
                                      'type': 'object'},
                                     {'$schema': 'http://json-schema.org/draft-04/schema#',
                                      'allOf': [{'$ref': '#/allOf/1/allOf/1/properties/additionalFiles/items/allOf/0'},
                                                {'properties': {'image': {'$ref': '#/allOf/0/allOf/1/properties/image/properties/thumbnail'},
                                                                'inline': {'type': 'boolean'},
                                                                'type': {'enum': ['image'],
                                                                         'type': 'string'}},
                                                 'required': ['type',
                                                              'image']}],
                                      'title': 'Image',
                                      'type': 'object'},
                                     {'$ref': '#/allOf/2/properties/acknowledgements/items/oneOf/0/oneOf/0/oneOf/2/properties/content/items/oneOf/1'},
                                     {'$ref': '#/allOf/1/allOf/1/properties/additionalFiles/items/allOf/0/properties/caption/items/oneOf/0'},
                                     {'$ref': '#/allOf/1/allOf/1/properties/ethics/items'},
                                     {'$schema': 'http://json-schema.org/draft-04/schema#',
                                      'properties': {'content': {'items': {'$ref': '#/allOf/1/allOf/1/properties/ethics/items'},
                                                                 'minItems': 1,
                                                                 'type': 'array'},
                                                     'image': {'$ref': '#/allOf/0/allOf/1/properties/image/properties/thumbnail'},
                                                     'type': {'enum': ['profile'],
                                                              'type': 'string'}},
                                      'required': ['type',
                                                   'image',
                                                   'content'],
                                      'title': 'Profile',
                                      'type': 'object'},
                                     {'$schema': 'http://json-schema.org/draft-04/schema#',
                                      'properties': {'answer': {'items': {'$ref': '#/allOf/1/allOf/1/properties/ethics/items'},
                                                                'minItems': 1,
                                                                'title': 'Answer',
                                                                'type': 'array'},
                                                     'question': {'minLength': 1,
                                                                  'title': 'Question',
                                                                  'type': 'string'},
                                                     'type': {'enum': ['question'],
                                                              'type': 'string'}},
                                      'required': ['type',
                                                   'question',
                                                   'answer'],
                                      'title': 'Question',
                                      'type': 'object'},
                                     {'$schema': 'http://json-schema.org/draft-04/schema#',
                                      'properties': {'cite': {'title': 'Citation',
                                                              'type': 'string'},
                                                     'text': {'items': {'$ref': '#/allOf/1/allOf/1/properties/ethics/items'},
                                                              'minItems': 1,
                                                              'title': 'Text',
                                                              'type': 'array'},
                                                     'type': {'enum': ['quote'],
                                                              'type': 'string'}},
                                      'required': ['type', 'text'],
                                      'title': 'Quote',
                                      'type': 'object'},
                                     {'$ref': '#/allOf/2/properties/acknowledgements/items/oneOf/0/oneOf/0/oneOf/2/properties/content/items/oneOf/4'},
                                     {'$schema': 'http://json-schema.org/draft-04/schema#',
                                      'allOf': [{'$ref': '#/allOf/1/allOf/1/properties/additionalFiles/items/allOf/0'},
                                                {'$ref': '#/allOf/1/allOf/1/properties/additionalFiles/items/allOf/1'},
                                                {'properties': {'autoplay': {'default': False,
                                                                             'title': 'Whether '
                                                                                      'to '
                                                                                      'autoplay '
                                                                                      'the '
                                                                                      'video.',
                                                                             'type': 'boolean'},
                                                                'height': {'minimum': 1,
                                                                           'title': 'Height',
                                                                           'type': 'integer'},
                                                                'loop': {'default': False,
                                                                         'title': 'Whether '
                                                                                  'to '
                                                                                  'loop '
                                                                                  'the '
                                                                                  'video.',
                                                                         'type': 'boolean'},
                                                                'placeholder': {'$ref': '#/allOf/0/allOf/1/properties/image/properties/thumbnail'},
                                                                'sources': {'items': {'properties': {'mediaType': {'allOf': [{'$ref': '#/allOf/1/allOf/1/properties/additionalFiles/items/allOf/3/properties/mediaType'},
                                                                                                                             {'pattern': '^video/'}]},
                                                                                                     'uri': {'format': 'uri',
                                                                                                             'pattern': '^https://',
                                                                                                             'title': 'URI',
                                                                                                             'type': 'string'}},
                                                                                      'required': ['mediaType',
                                                                                                   'uri'],
                                                                                      'type': 'object'},
                                                                            'minItems': 1,
                                                                            'type': 'array'},
                                                                'type': {'enum': ['video'],
                                                                         'type': 'string'},
                                                                'width': {'minimum': 1,
                                                                          'title': 'Width',
                                                                          'type': 'integer'}},
                                                 'required': ['type',
                                                              'sources',
                                                              'width',
                                                              'height']}],
                                      'title': 'Video',
                                      'type': 'object'},
                                     {'$schema': 'http://json-schema.org/draft-04/schema#',
                                      'properties': {'height': {'minimum': 1,
                                                                'title': 'Height',
                                                                'type': 'integer'},
                                                     'id': {'title': 'Video '
                                                                     'ID',
                                                            'type': 'string'},
                                                     'type': {'enum': ['youtube'],
                                                              'type': 'string'},
                                                     'width': {'minimum': 1,
                                                               'title': 'Width',
                                                               'type': 'integer'}},
                                      'required': ['type',
                                                   'id',
                                                   'width',
                                                   'height'],
                                      'title': 'YouTube video',
                                      'type': 'object'}]},
                          {'$schema': 'http://json-schema.org/draft-04/schema#',
                           'dependencies': {'doi': ['id']},
                           'properties': {'content': {'description': 'Content',
                                                      'items': {'$ref': '#/allOf/2/properties/acknowledgements/items/oneOf/0/oneOf/0'},
                                                      'minItems': 1,
                                                      'type': 'array'},
                                          'doi': {'$ref': '#/allOf/0/allOf/0/properties/doi'},
                                          'id': {'$ref': '#/allOf/2/properties/appendices/items/properties/id'},
                                          'label': {'minLength': 1,
                                                    'title': 'Label',
                                                    'type': 'string'},
                                          'title': {'minLength': 1,
                                                    'title': 'Title',
                                                    'type': 'string'},
                                          'type': {'enum': ['box'],
                                                   'type': 'string'}},
                           'required': ['type', 'title', 'content'],
                           'title': 'Box',
                           'type': 'object'}]},
               {'$ref': '#/allOf/2/properties/body/items/allOf/0'}]}

On instance['appendices'][0]['content'][0]:
    {'content': [{'text': 'In order to prepare for this Kitchen sink we '
                          'reviewed our archive and found common errors or '
                          'miscommunication from the archive, tagging of '
                          '<a href="#app1fig1">Appendix '
                          '1—Figure                          1</a> is a '
                          'classic example and here the tagging is '
                          'updated. Appendices figures can also have '
                          'figure supplements, for example <a '
                          'href="#app1fig1s1">Appendix '
                          '1—Figure                              1—Figure '
                          'Supplement 1</a> (<a href="#bib25">Koch, '
                          '1959</a>).',
                  'type': 'paragraph'},
                 {'assets': [{'caption': [{'text': 'If there is a caption '
                                                   'to accompany the title '
                                                   'it would display here '
                                                   '(<a '
                                                   'href="#bib25">Koch, '
                                                   '1959</a>).',
                                           'type': 'paragraph'}],
                              'doi': '10.7554/eLife.00666.024',
                              'id': 'app1fig1',
                              'image': {'alt': '',
                                        'size': {'height': None,
                                                 'width': None},
                                        'source': {'filename': 'elife-00666-app1-fig1.jpg',
                                                   'mediaType': 'image/jpeg',
                                                   'uri': 'https://iiif.elifesciences.org/lax/00666%2Felife-00666-app1-fig1.tif/full/full/0/default.jpg'},
                                        'uri': 'https://iiif.elifesciences.org/lax/00666%2Felife-00666-app1-fig1.tif'},
                              'label': 'Appendix 1—Figure 1',
                              'title': 'Appendix figure title.\n'
                                       '                        ',
                              'type': 'image'},
                             {'caption': [{'text': 'If there is a caption '
                                                   'to accompany the title '
                                                   'it would display here.',
                                           'type': 'paragraph'}],
                              'doi': '10.7554/eLife.00666.025',
                              'id': 'app1fig1s1',
                              'image': {'alt': '',
                                        'size': {'height': None,
                                                 'width': None},
                                        'source': {'filename': 'elife-00666-app1-fig1-figsupp1.jpg',
                                                   'mediaType': 'image/jpeg',
                                                   'uri': 'https://iiif.elifesciences.org/lax/00666%2Felife-00666-app1-fig1-figsupp1.tif/full/full/0/default.jpg'},
                                        'uri': 'https://iiif.elifesciences.org/lax/00666%2Felife-00666-app1-fig1-figsupp1.tif'},
                              'label': 'Appendix 1—Figure 1—Figure '
                                       'Supplement 1',
                              'title': 'Appendix figure supplement title.',
                              'type': 'image'}],
                  'type': 'figure'},
                 {'content': [{'text': 'This is the text of the content of '
                                       'subheading 1 within appendix 2. In '
                                       'some cases, authors will use 1.1, '
                                       '1.2, 1.2.1, 1.2.2, 1.3 etc as '
                                       'prefixes to their headings. We '
                                       'retain this '
                                       'in                                 '
                                       'the appendix sections only and '
                                       'allow them to cite these as '
                                       'Appendix 1.1, Appendix 1.2 etc in '
                                       'the main text. This is entirely '
                                       'optional on the part of the '
                                       'authors and articles may '
                                       'or                             may '
                                       'not include this style of '
                                       'heading/citation. This style of '
                                       'heading/citation is not allowed '
                                       'for main text headings.',
                               'type': 'paragraph'}],
                  'id': 's8-1',
                  'title': '1.1 Sub heading',
                  'type': 'section'},
                 {'content': [{'text': 'This is the text of the content of '
                                       'subheading 2 within appendix 2.',
                               'type': 'paragraph'},
                              {'assets': [{'caption': [{'text': 'This is '
                                                                'the '
                                                                'caption: '
                                                                'A table '
                                                                'containing '
                                                                'interesting '
                                                                'formating '
                                                                'that is '
                                                                'large '
                                                                'enough to '
                                                                'require '
                                                                'landscape '
                                                                'orientation '
                                                                'in the '
                                                                'PDF.',
                                                        'type': 'paragraph'}],
                                           'doi': '10.7554/eLife.00666.039',
                                           'footnotes': [{'text': [{'text': 'Footnotes '
                                                                            'not '
                                                                            'linked '
                                                                            'to '
                                                                            'content '
                                                                            'within '
                                                                            'the '
                                                                            'table '
                                                                            'text '
                                                                            'are '
                                                                            'usually '
                                                                            'to '
                                                                            'define '
                                                                            'abbreviations. '
                                                                            'For '
                                                                            'example:',
                                                                    'type': 'paragraph'},
                                                                   {'text': 'WT, '
                                                                            'wild '
                                                                            'type.',
                                                                    'type': 'paragraph'}]}],
                                           'id': 'app1table1',
                                           'label': 'Apendix 1—Table 1',
                                           'tables': ['<table>\n'
                                                      '<thead>\n'
                                                      '\n'
                                                      '<tr>\n'
                                                      '\n'
                                                      '<th colspan="3" '
                                                      'rowspan="2">\u2009'
                                                      '</th>\n'
                                                      '<th align="center" '
                                                      'colspan="8">GLVs '
                                                      '(percent IS '
                                                      'plant<sup>-1</sup>)</th>\n'
                                                      '<th align="center" '
                                                      'colspan="17">TPS10 '
                                                      'products (percent '
                                                      'IS '
                                                      'plant<sup>-1</sup>)</th>\n'
                                                      '<th align="center" '
                                                      'colspan="10">Non-target '
                                                      'volatiles (percent '
                                                      'IS '
                                                      'plant<sup>-1</sup>)</th>\n'
                                                      '</tr>\n'
                                                      '<tr>\n'
                                                      '<th align="center" '
                                                      'colspan="8">(<i>Z</i>)-Hexen-3-ol</th>\n'
                                                      '<th align="center" '
                                                      'colspan="10">TAB</th><th '
                                                      'align="center" '
                                                      'colspan="7">TBF</th>\n'
                                                      '<th align="center" '
                                                      'colspan="6">α-Duprezianene</th>\n'
                                                      '<th align="center" '
                                                      'colspan="4">Germacrene '
                                                      'A</th>\n'
                                                      '</tr>\n'
                                                      '</thead>\n'
                                                      '<tbody>\n'
                                                      '\n'
                                                      '<tr>\n'
                                                      '<td><b>Genotype</b></td>\n'
                                                      '<td><b>Day '
                                                      'n</b></td>\n'
                                                      '<td><b>Night '
                                                      'n</b></td>\n'
                                                      '<td '
                                                      'colspan="3"><b>Day</b></td>\n'
                                                      '<td '
                                                      'colspan="5"><b>Night</b></td>\n'
                                                      '<td '
                                                      'colspan="4"><b>Day</b></td>\n'
                                                      '<td '
                                                      'colspan="6"><b>Night</b></td>\n'
                                                      '<td '
                                                      'colspan="4"><b>Day</b></td>\n'
                                                      '<td '
                                                      'colspan="3"><b>Night</b></td>\n'
                                                      '<td '
                                                      'colspan="3"><b>Day</b></td>\n'
                                                      '<td '
                                                      'colspan="3"><b>Night</b></td>\n'
                                                      '<td '
                                                      'colspan="3"><b>Day</b></td>\n'
                                                      '<td><b>Night</b></td>\n'
                                                      '</tr>\n'
                                                      '<tr>\n'
                                                      '<td><b>WT</b></td>\n'
                                                      '<td>8</td><td>8</td>\n'
                                                      '<td>0.99%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>0.99%</td>\n'
                                                      '<td>7.96%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>4.25%</td>\n'
                                                      '\n'
                                                      '<td rowspan="2" '
                                                      'valign="middle"><span '
                                                      'class="author-callout-style-a1">}</span></td>\n'
                                                      '<td rowspan="2" '
                                                      'valign="middle"><b><span '
                                                      'class="author-callout-style-a1">a</span></b><sub><b><span '
                                                      'class="author-callout-style-a1">lox</span></b></sub></td>\n'
                                                      '<td>0.37%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>0.29%</td>\n'
                                                      '<td><b><span '
                                                      'class="author-callout-style-a1">a</span></b></td>\n'
                                                      '<td '
                                                      'colspan="3">—</td>\n'
                                                      '<td>\u2009</td>\n'
                                                      '<td rowspan="3" '
                                                      'valign="middle"><span '
                                                      'class="author-callout-style-a1">}</span></td>\n'
                                                      '<td rowspan="2" '
                                                      'valign="bottom"><b><span '
                                                      'class="author-callout-style-a1">a</span></b><sub><b><span '
                                                      'class="author-callout-style-a1">TPS</span></b></sub></td>\n'
                                                      '<td '
                                                      'colspan="3">—</td>\n'
                                                      '<td><b><span '
                                                      'class="author-callout-style-a1">a</span></b></td>\n'
                                                      '<td '
                                                      'colspan="3">—</td>\n'
                                                      '\n'
                                                      '<td><span '
                                                      'class="author-callout-style-a2">2.13%</span></td>\n'
                                                      '<td><span '
                                                      'class="author-callout-style-a2">±</span></td>\n'
                                                      '<td><span '
                                                      'class="author-callout-style-a2">0.85%</span></td>\n'
                                                      '<td><span '
                                                      'class="author-callout-style-a2">0.96%</span></td>\n'
                                                      '<td><span '
                                                      'class="author-callout-style-a2">±</span></td>\n'
                                                      '<td><span '
                                                      'class="author-callout-style-a2">0.42%</span></td>\n'
                                                      '<td><span '
                                                      'class="author-callout-style-a2">1.68%</span></td>\n'
                                                      '<td><span '
                                                      'class="author-callout-style-a2">±</span></td>\n'
                                                      '<td><span '
                                                      'class="author-callout-style-a2">0.98%</span></td>\n'
                                                      '<td>—</td>\n'
                                                      '</tr>\n'
                                                      '<tr>\n'
                                                      '<td><b><i>TPS10</i></b></td>\n'
                                                      '<td>7</td>\n'
                                                      '<td>7</td>\n'
                                                      '<td>2.37%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>1.55%</td>\n'
                                                      '<td>2.84%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>0.63%</td>\n'
                                                      '<td>18.97%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>6.03%</td>\n'
                                                      '\n'
                                                      '<td><b><span '
                                                      'class="author-callout-style-a3">b</span></b></td>\n'
                                                      '<td>0.94%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>0.53%</td>\n'
                                                      '<td rowspan="3" '
                                                      'valign="middle"><span '
                                                      'class="author-callout-style-a3">}</span></td>\n'
                                                      '<td>9.34%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>3.44%</td>\n'
                                                      '<td><b><span '
                                                      'class="author-callout-style-a3">b</span></b></td>\n'
                                                      '<td>0.20%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>0.20%</td>\n'
                                                      '<td>9.47%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>5.26%</td>\n'
                                                      '<td>0.94%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>0.26%</td>\n'
                                                      '<td>2.78%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>1.52%</td>\n'
                                                      '<td>—</td>\n'
                                                      '</tr>\n'
                                                      '<tr>\n'
                                                      '<td><b><i>lox2/3</i></b></td>\n'
                                                      '<td>7</td>\n'
                                                      '<td>8</td>\n'
                                                      '<td>0.13%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>0.13%</td>\n'
                                                      '<td>1.06%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>0.64%</td>\n'
                                                      '<td rowspan="2" '
                                                      'valign="middle"><span '
                                                      'class="author-callout-style-a3">}</span></td>\n'
                                                      '<td rowspan="2" '
                                                      'valign="middle"><b><span '
                                                      'class="author-callout-style-a3">b</span></b><sub><b><span '
                                                      'class="author-callout-style-a3">lox</span></b></sub></td>\n'
                                                      '<td '
                                                      'colspan="3">—</td>\n'
                                                      '<td><b><span '
                                                      'class="author-callout-style-a1">a</span></b></td>\n'
                                                      '<td>0.15%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>0.15%</td>\n'
                                                      '<td '
                                                      'rowspan="2"><b><span '
                                                      'class="author-callout-style-a3">b</span></b><sub><b><span '
                                                      'class="author-callout-style-a3">TPS</span></b></sub></td>\n'
                                                      '<td '
                                                      'colspan="3">—</td>\n'
                                                      '<td><b><span '
                                                      'class="author-callout-style-a1">a</span></b></td>\n'
                                                      '<td '
                                                      'colspan="3">—</td>\n'
                                                      '<td>2.75%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>1.12%</td>\n'
                                                      '<td>0.60%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>0.19%</td>\n'
                                                      '<td>1.68%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>1.49%</td>\n'
                                                      '<td>—</td>\n'
                                                      '</tr>\n'
                                                      '<tr>\n'
                                                      '<td><b><i>lox2/3</i>x<i>TPS10</i></b></td>\n'
                                                      '<td>7</td>\n'
                                                      '<td>7</td>\n'
                                                      '<td>0.07%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>0.07%</td>\n'
                                                      '<td>1.24%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>0.84%</td>\n'
                                                      '<td>7.39%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>2.56%</td>\n'
                                                      '<td><b><span '
                                                      'class="author-callout-style-a3">b</span></b></td>\n'
                                                      '<td>2.08%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>0.84%</td>\n'
                                                      '<td>\u2009</td>\n'
                                                      '<td>4.47%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>1.70%</td>\n'
                                                      '<td><b><span '
                                                      'class="author-callout-style-a3">b</span></b></td>\n'
                                                      '<td>0.40%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>0.40%</td>\n'
                                                      '<td>3.02%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>1.42%</td>\n'
                                                      '<td>0.73%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>0.31%</td>\n'
                                                      '<td>0.66%</td>\n'
                                                      '<td>±</td>\n'
                                                      '<td>0.37%</td>\n'
                                                      '<td>—</td>\n'
                                                      '</tr>\n'
                                                      '</tbody>\n'
                                                      '</table>'],
                                           'title': 'This is the title.',
                                           'type': 'table'}],
                               'type': 'figure'}],
                  'id': 's8-2',
                  'title': '1.2 Sub heading',
                  'type': 'section'}],
     'doi': '10.7554/eLife.00666.023',
     'id': 's8',
     'title': 'Preparation',
     'type': 'section'} -- {"version": 1, "msid": "00666", "json-filename": "elife-00666-v1.json", "stack_info": null}
```

**Comment by thewilkybarkid** [comment]
Interestingly that's the other appendix (`Appendix 1`)...

**Comment by gnott** [comment]
I've tried generating and validation the JSON for the latest 00666 XML kitchen sink locally, and after some tiny tweaks (replacing all image width and heights with 1 instead of None) the output is validating for me. It could be that simple? I'm not sure whether these particular tests use real IIIF data or if they are mocked. There should probably be no `'height': None, 'width': None` anywhere in order to validate, as @thewilkybarkid has pointed out.

**Comment by giorgiosironi** [comment]
Re-running the `elife-spectrum` build shows a similar error:
```
{
  "datetime": "2018-11-26T13:13:59.999943",
  "name": "__main__",
  "message": "invalid response",
  "module": "adaptor",
  "lineno": 213,
  "levelname": "ERROR",
  "funcName": "mkresponse",
  "filename": "adaptor.py",
  "asctime": "2018-11-26 13:14:00,001",
  "pathname": "src/adaptor.py",
  "token": "eyJzdGF0dXMiOiAidm9yIiwgInJ1bl90eXBlIjogImluaXRpYWwtYXJ0aWNsZSIsICJmb3JjZSI6\nIGZhbHNlLCAiZXhwYW5kZWRfZm9sZGVyIjogIjg1NzQ2OTEwODc5MjMyMDA2NjYuMS9hY2JmMmNm\nNC$2OWNlLTQyMzUtYTU4ZS1hYThhZDZmMjZjYWQiLCAidmVyc2lvbiI6ICIxIiwgInJ1biI6ICJh\nY2JmMmNmNC02OWNlLTQyMzUtYTU4ZS1hYThhZDZmMjZjYWQifQ==\n",
  "status-message": "(error 1 of 1)\n\nData fails to validate against multiple schemas.\nPossible reasons (smallest, most relevant, errors first):\n\n1. None is not of ty$e 'integer'\n\n2. None is not of type 'integer'\n\n3. 'figure' is not one of ['button']\n\n4. 'figure' is not one of ['code']\n\n5. 'figure' is not one of ['excerpt']\n\n$. 'image' is not one of ['table']\n\n7. 'image' is not one of ['video']\n\n8. 'figure' is not one of ['image']\n\n9. 'figure' is not one of ['list']\n\n10. 'figure' is no$ one of ['mathml']\n\nThe full errors including their schema are attached to this error as a 'trace', indexed by their number above.\n",
  "id": "8574691087923200666",
  "validate-only": false,
  "requested-action": "ingest",
  "force": false,
  "status": "invalid"
}
```
In fact we have no such `app2-fig1` image in the current kitchen sink assets:
```
$ ls -l spectrum/templates/elife-00666-vor-r1/elife-00666-app*
-rw-rw-r-- 1 giorgio giorgio  5014444 Jun  5 16:42 spectrum/templates/elife-00666-vor-r1/elife-00666-app1-fig1-figsupp1.tif
-rw-rw-r-- 1 giorgio giorgio  5148040 Jun  5 16:42 spectrum/templates/elife-00666-vor-r1/elife-00666-app1-fig1.tif
-rw-rw-r-- 1 giorgio giorgio 43579604 Jun  5 16:42 spectrum/templates/elife-00666-vor-r1/elife-00666-app2-video1.mp4
```
This automated build copies the XML from https://github.com/elifesciences/XML-mapping but there is no image there, so where do we find it?

**Comment by gnott** [comment]
Tests are passing after I added a `elife-00666-app2-fig1.tif` file - looks like we diagnosed it correctly!

**Comment by giorgiosironi** [comment]
Thank you. Is that a random file or the one that we should use going forward?

**Comment by gnott** [comment]
The images I viewed are just samples, and the new one I created by cropping one of the existing images. The content itself doesn't matter according to Production.

**Comment by giorgiosironi** [comment]
@FAtherden-eLife merging this unless you want a special image to be used.

**Comment by FAtherden-eLife** [comment]
Sorry @giorgiosironi, only just seen this - yes that's fine with me thanks!

**Pull request merged**
