### PR TITLE
Allow Python 3.6

### PR DESCRIPTION
**Pull request by giorgiosironi**
Fiddled on `elife-libraries--spectrum` to make the simplest possible test work.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Need to get Python 3.6 locally, Pylint fails in dozens of places.

**Comment by giorgiosironi** [comment]
Have to verify this still works on Python 3.5 locally.

**Comment by giorgiosironi** [comment]
`./execute-simplest-possible-test.sh` miraculously works locally despite errors on installation, trying the larger suite.

**Comment by giorgiosironi** [comment]
This really needs a split in `requirements.txt` and `requirements.lock` or similar, but for now it will do.

**Comment by lsh-0** [comment]
> This really needs a split in requirements.txt and requirements.lock or similar, but for now it will do.

pipenv might be the way to go. I don't particularly like it, but it seems to have been adopted by Pypa and is being recommended in the documentation for Pypi. I have no experience with Poetry but I hear some prefer it. We should pick one and start using it.

**Comment by giorgiosironi** [comment]
We previously picked pipenv, didn't work, and switched to Poetry, and then I don't remember what happened.

**Pull request merged**
