### PR TITLE
Updated kitchen sinks from Github (elife-00777.xml,elife-1234567890.xml)

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-elife-spectrum-update-kitchen-sinks-github/980/display/redirect which resulted in this pull request.

### CODE REVIEW

**Comment by lsh-0** [comment]
fyi @gnott , an interesting regression here because of videos being excluded from having their paths turned into jinja placeholders.

Doesn't appear to have affected the tests but I'll keep it in the back of my head.

**Comment by gnott** [comment]
Possibly related to how `elife-bot` includes the hack to use the last five digits of the article id when checking for Glencoe metadata, yet it downloads the JPG images using the full randomised article id.

**Comment by lsh-0** [comment]
I'm tracking down a problem with a few of the builds right now that may or may not be related to this:

* https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects/elife-spectrum/detail/PR-270/2/pipeline/
* https://alfred.elifesciences.org/job/test-elife-spectrum/440/

looks like /recommendations is failing after talking to whatever is serving up podcasts (journal-cms ?). Anyway, once I'm done spelunking I'll update this thread.

**Comment by lsh-0** [comment]
hrm - journal-cms was returning a 500 for "http://localhost/podcast-episodes?page=1&containing%5B%5D=article%2F149121021234567890&per-page=100&order=desc" before a highstate and now it isn't. 

No other visible errors unfortunately. Kicking builds ...

**Pull request merged**
