### PR TITLE
Updated kitchen sinks from Github (elife-00777.xml,elife-00666.xml)

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-elife-spectrum-update-kitchen-sinks-github/553/display/redirect which resulted in this pull request.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Various failure in services like `search`, `elife-xpub`; not reproducible.

**Comment by giorgiosironi** [comment]
[Last failure](https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Felife-spectrum/detail/PR-174/7/pipeline) is only on `observer`, doing some quick checks.

**Comment by giorgiosironi** [comment]
```
● update-listener.service - "Observer article update listener"
   Loaded: loaded (/lib/systemd/system/update-listener.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2019-05-17 14:54:48 UTC; 18min ago
  Process: 1434 ExecStart=/srv/observer/venv/bin/newrelic-admin run-program /srv/observer/venv/bin/python src/manage.py update_listener (code=exited, status=1/FAILURE)
 Main PID: 1434 (code=exited, status=1/FAILURE)

May 17 14:54:48 end2end--observer.elifesciences.org systemd[1]: update-listener.service: Main process exited, code=exited, status=1/FAILURE
May 17 14:54:48 end2end--observer.elifesciences.org systemd[1]: update-listener.service: Failed with result 'exit-code'.
May 17 14:54:48 end2end--observer.elifesciences.org systemd[1]: update-listener.service: Service hold-off time over, scheduling restart.
May 17 14:54:48 end2end--observer.elifesciences.org systemd[1]: update-listener.service: Scheduled restart job, restart counter is at 5.
May 17 14:54:48 end2end--observer.elifesciences.org systemd[1]: Stopped "Observer article update listener".
May 17 14:54:48 end2end--observer.elifesciences.org systemd[1]: update-listener.service: Start request repeated too quickly.
May 17 14:54:48 end2end--observer.elifesciences.org systemd[1]: update-listener.service: Failed with result 'exit-code'.
May 17 14:54:48 end2end--observer.elifesciences.org systemd[1]: Failed to start "Observer article update listener".
```

**Comment by giorgiosironi** [comment]
```
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]: Traceback (most recent call last):
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:   File "src/manage.py", line 23, in <module>
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:     execute_from_command_line(sys.argv)
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:   File "/srv/observer/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, i
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:     utility.execute()
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:   File "/srv/observer/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, i
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:     self.fetch_command(subcommand).run_from_argv(self.argv)
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:   File "/srv/observer/venv/lib/python3.6/site-packages/newrelic/hooks/framework_django.py", line 983, i
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:     return wrapped(*args, **kwargs)
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:   File "/srv/observer/venv/lib/python3.6/site-packages/django/core/management/base.py", line 283, in ru
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:     self.execute(*args, **cmd_options)
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:   File "/srv/observer/venv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in ex
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:     output = self.handle(*args, **options)
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:   File "/srv/observer/venv/lib/python3.6/site-packages/newrelic/api/function_trace.py", line 109, in li
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:     return wrapped(*args, **kwargs)
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:   File "/srv/observer/src/observer/management/commands/update_listener.py", line 29, in handle
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:     any(handler(event) for event in inc.poll(inc.queue(settings.EVENT_QUEUE)))
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:   File "/srv/observer/src/observer/inc.py", line 18, in queue
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:     return boto3.resource('sqs').get_queue_by_name(QueueName=name)
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:   File "/srv/observer/venv/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_act
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:     response = action(self, *args, **kwargs)
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:   File "/srv/observer/venv/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:     response = getattr(parent.meta.client, operation_name)(**params)
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:   File "/srv/observer/venv/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:     return self._make_api_call(operation_name, kwargs)
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:   File "/srv/observer/venv/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]:     raise error_class(parsed_response, operation_name)
May 17 14:54:47 end2end--observer.elifesciences.org observer[1434]: botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the GetQueueUrl
```
Credentials?

**Comment by giorgiosironi** [comment]
An highstate seems to have fixed it, this problem may happen again with other `end2end` stacks. /cc @lsh-0

**Comment by lsh-0** [comment]
cheers, @giorgiosironi 

I'll check up on it today. 

> botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the GetQueueUrl

my first guess would be the new credentials, but I suspect a ClientTokenId might be something else

**Comment by giorgiosironi** [comment]
I think it was just the new credentials yes, they were not being propagated without a new deploy having been made.

**Pull request merged**
