### PR TITLE
PLEASE DO NOT MERGE - Kitchen sink 00666 test

### PR DESCRIPTION
**Pull request by gnott**
I'm testing whether altering the video XML in a `00666` article template will allow the tests to pass.

### CODE REVIEW

**Comment by lsh-0** [comment]
I'm looking at the changes you've made here so I can fix up the references in the renamed kitchen-sink XML happening [here](https://github.com/elifesciences/XML-mapping/pull/107).

It looks like you've removed a reference to a video, changed two `xref`s and renamed a bunch of images.

Renaming images is fine and easy, but if I wanted to keep the video how do I deposit it with glencoe? Or does that happen as part of each elife-spectrum test run?  And if so ... are these test videos accumulating in Glencoe?

**Comment by gnott** [comment]
What I remember about Glencoe videos is a deposit to them includes an XML file containing the `<media>` elements including `@id` attributes and includes the videos themselves. I haven't done these deposits before though and the video files are deposited by the typesetter, although Production can probably track down how to deposit videos better than I can.

**Comment by lsh-0** [comment]
That's pretty interesting, thanks. I'd been assuming it was something elife-bot was doing.

**Comment by lsh-0** [comment]
I found this: https://github.com/elifesciences/schematron-gitbook/blob/master/toolkit/glencoe.md

which is pretty impressive.

**Comment by lsh-0** [comment]
thanks for your work on this , it was helpful wrangling the kitchen sink recently.

**Pull request closed without merging**
