### PR TITLE
Commenting out related articles

### PR DESCRIPTION
**Pull request by giorgiosironi**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
```
curl https://end2end--gateway.elifesciences.org/articles/37746979165015893/related | jq "."
[]
```
but Journal explodes on:
```
  "message": "Uncaught PHP Exception Symfony\\Component\\Debug\\Exception\\FatalThrowableError: \"Call to a member function getId() on null\" at /srv/journal/src/Controller/ArticlesController.php line 648"
```
which seems to load related-articles. It assumes that there is always a related article when the article type is a correction or a retraction...

**Comment by thewilkybarkid** [comment]
We could make it fail gracefully, but it's correct that every correction and retraction article will have a single related article.

**Comment by giorgiosironi** [comment]
Graceful visualization of this article would allow not only `end2end` but also the testing environment `continuumtest` to load corrections and retraction without the original article being there. Pushes for consistency that spans on the single article (and its versions), but is not system-wide.

**Comment by giorgiosironi** [comment]
Not needed anymore!

**Pull request closed without merging**
