### PR TITLE
Updated kitchen sinks from Github (elife-00777.xml,elife-00666.xml)

### PR DESCRIPTION
**Pull request by elife-alfred-user**
I have run https://alfred.elifesciences.org/job/dependencies/job/dependencies-elife-spectrum-update-kitchen-sinks-github/348/display/redirect which resulted in this pull request.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Dashboard DNS failure on the first attempt, but being tested.

**Comment by giorgiosironi** [comment]
No failure, because it's backward compatible and doesn't make the page explode. The change will probably be more subtle in the HTML of Journal.

**Comment by thewilkybarkid** [comment]
Does this trigger it going into `continuumtest`? Haven't found what triggers that.

**Comment by giorgiosironi** [comment]
No, this PR is tested into `end2end` and when merged https://alfred.elifesciences.org/job/test-elife-spectrum/ runs on `end2end` too. https://alfred.elifesciences.org/job/test-continuumtest/451/console runs daily a spectrum smoke test on `continuumtest`, with the intent to make sure that environment keeps working.

**Comment by thewilkybarkid** [comment]
Do you know how https://continuumtest--journal.elifesciences.org/articles/00666 is updated?

**Pull request merged**
