### PR TITLE
Setting Referer on Journal log in

### PR DESCRIPTION
**Pull request by giorgiosironi**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
3 tests are failed and the run is completing, now I'll rollback end2end too, get it green, and merge.

**Comment by giorgiosironi** [comment]
https://alfred.elifesciences.org/job/pull-requests-projects/job/elife-spectrum/job/PR-99/3/console should be green.

**Comment by giorgiosironi** [comment]
1 failed but was a race condition, log in works.

**Comment by thewilkybarkid** [comment]
When we revisit this, it should go through the CDN too (that would have found the other issue of it not being passed through).

**Pull request merged**
