### PR TITLE
Added check on dashboard's preview-link field

### PR DESCRIPTION
**Pull request by giorgiosironi**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Will have to add that this actually loads with 200.

**Comment by giorgiosironi** [comment]
We may not be able to load preview on end2end because we don't have a `journal--end2endpreview`... wonder how the current tests (that generate the preview URL themselves) work.

**Comment by Jenniferstrej** [comment]
Ok. I was looking into doing the change, but since it's the first time I was still working my way around the app :). I thought we could check the data model for the details page from the api and on

```
def ready_to_publish(self, id, version, run=None, run_after=None):
        return self._wait_for_status(id, version, run=run, status="ready to publish", run_after=run_after)
```

have the path checked

```
def ready_to_publish(self, id, version, run=None, run_after=None, preview_path):
        return self._wait_for_status(id, version, run=run, status="ready to publish", run_after=run_after, preview_path)
```

**Comment by giorgiosironi** [comment]
I'll move the check inside there since by definition there must be a preview every time an article is ready to publish.

**Comment by giorgiosironi** [comment]
Had one test failure because it needs `master` merged in (https://github.com/elifesciences/elife-spectrum/pull/95)

**Pull request merged**
